name: Update Player Points Daily

on:
  schedule:
    - cron: '30 5 * * *' # Runs every day at 5:30 AM UTC
  workflow_dispatch:     # Also allows manual trigger from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Decrypt Firebase Service Account
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > ./serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Run updatePlayerPoints.ts
        run: npx ts-node scripts/updatePlayerPoints.ts
      - name: Run updateTeamLeaderboard.ts
        run: npx ts-node scripts/updateTeamLeaderboard.js
